name: Moleculer S3 AWS CodeBulid

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          audience: sts.amazonaws.com
          role-to-assume: arn:aws:iam::${{ vars.ACCOUNT_ID }}:role/GitHubActionsRole
          aws-region: ${{ vars.REGION }}

      - name: Trigger AWS CodeBuild and Upload files to S3
        uses: aws-actions/aws-codebuild-run-build@v1
        with:
          project-name: GitHubActionsRunnerMoleculerProject
          buildspec-override:   |
            version: 0.2
            phases:
              install:
                commands:
                  - echo "Installing dependencies"
              build:
                commands:
                  - echo "Copying files to S3"
                  - aws s3 cp js/ s3://${{ vars.S3_BUCKET }}/js/ --recursive
                  - aws s3 cp sh/ s3://${{ vars.S3_BUCKET }}/sh/ --recursive
            artifacts:
              files:
                - '**/*'
