name: Moleculer AWS CodeBuild

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          audience: sts.amazonaws.com
          role-to-assume: arn:aws:iam::448049806923:role/GitHubActionsRole
          aws-region: ap-southeast-1

      - name: Trigger AWS CodeBuild and Run Terraform
        uses: aws-actions/aws-codebuild-run-build@v1
        with:
          project-name: GitHubActionsRunnerMoleculerProject
          buildspec-override:   |
            version: 0.2
            phases:
              install:
                commands:
                  - echo "Installing dependencies, if any"
              build:
                commands:
                  - echo "Copying files to S3"
                  - aws s3 cp js/ s3://${{ env.S3_BUCKET }}/js/ --recursive
                  - aws s3 cp sh/ s3://${{ env.S3_BUCKET }}/sh/ --recursive
            artifacts:
              files:
                - '**/*'
