name: Moleculer Terraform AWS CodeBulid

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          audience: sts.amazonaws.com
          role-to-assume: arn:aws:iam::448049806923:role/GitHubActionsRole
          aws-region: ap-southeast-1

      - name: Trigger AWS CodeBuild and Run Terraform
        uses: aws-actions/aws-codebuild-run-build@v1
        with:
          project-name: GitHubActionsRunnerMoleculerProject
          buildspec-override:   |
            version: 0.2
            phases:
              install:
                commands:
                  - echo "Installing Terraform"
                  - curl -LO "https://releases.hashicorp.com/terraform/$(terraform version -json | jq -r .current_version)/terraform_$(terraform version -json | jq -r .current_version)_linux_amd64.zip"
                  - unzip terraform_$(terraform version -json | jq -r .current_version)_linux_amd64.zip
                  - mv terraform /usr/local/bin/
              pre_build:
                commands:
                  - cd terraform/code/nonprod
                  - echo "Initializing Terraform"
                  - terraform init -reconfigure -backend-config=../../config/Backend.conf
              build:
                commands:
                  - echo "Applying Terraform configuration"
                  - terraform plan -var-file=../../config/values.tfvars
            artifacts:
              files:
                - '**/*'
